---
abstract: 'Add a blame() method to L<Git::Repository>.'
author:
  - 'Guillaume Aubert <aubertg@cpan.org>'
build_requires:
  Carp: 0
  Data::Dumper: 0
  Git::Repository: 1.2
  Perl6::Slurp: 0
  Test::Deep: 0
  Test::Exception: 0
  Test::Git: 0
  Test::More: 0
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Git-Repository-Plugin-Blame
provides:
  Git::Repository::Plugin::Blame:
    file: lib/Git/Repository/Plugin/Blame.pm
    version: v1.0.4
  Git::Repository::Plugin::Blame::Line:
    file: lib/Git/Repository/Plugin/Blame/Line.pm
    version: v1.0.4
requires:
  perl: 5.006
resources:
  bugtracker: https://github.com/guillaumeaubert/Git-Repository-Plugin-Blame/issues
  homepage: https://metacpan.org/release/Git-Repository-Plugin-Blame
  license: http://www.gnu.org/licenses/gpl-3.0.txt
  repository: https://github.com/guillaumeaubert/Git-Repository-Plugin-Blame
version: v1.0.4
