---
abstract: 'Add a blame() method to L<Git::Repository>.'
author:
  - 'Guillaume Aubert <aubertg@cpan.org>'
build_requires:
  Data::Dumper: '0'
  Test::Deep: '0'
  Test::Exception: '0'
  Test::FailWarnings: '0'
  Test::Git: '0'
  Test::More: '0'
  Test::Requires::Git: '1.005'
  Test::Type: '0'
configure_requires:
  Module::Build: '0'
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Git-Repository-Plugin-Blame
provides:
  Git::Repository::Plugin::Blame:
    file: lib/Git/Repository/Plugin/Blame.pm
    version: v1.4.0
  Git::Repository::Plugin::Blame::Cache:
    file: lib/Git/Repository/Plugin/Blame/Cache.pm
    version: v1.4.0
  Git::Repository::Plugin::Blame::Line:
    file: lib/Git/Repository/Plugin/Blame/Line.pm
    version: v1.4.0
requires:
  Carp: '0'
  Class::Load: '0.2'
  Data::Validate::Type: '0'
  Git::Repository: '1.2'
  Git::Repository::Plugin::Log: '0'
  Perl6::Slurp: '0'
  perl: '5.006'
resources:
  bugtracker: https://github.com/guillaumeaubert/Git-Repository-Plugin-Blame/issues
  homepage: https://metacpan.org/release/Git-Repository-Plugin-Blame
  license: http://dev.perl.org/licenses/
  repository: https://github.com/guillaumeaubert/Git-Repository-Plugin-Blame
version: v1.4.0
